### PR TITLE
Add Maven Central badge

### PR DESCRIPTION
**Pull request by szpak**
Add Maven Central badge which makes it easier to get (just after a click) a ready to copy-paste code snippet to put into Maven/Gradle/Sbt/other build configuration file.

### CODE REVIEW

**Comment by adietish** [comment]
Thanks for the patch, but I cannot getch from your fork. Did you delete it?

**Comment by szpak** [comment]
No, it is still there. Even GH displays that it can be merged automatically. The fork and branch were created automatically from GH GUI, but it shouldn't matter.

What commands do you call to fetch my branch?

**Comment by szpak** [comment]
I've just checked it and the following commands worked fine:
```
git fetch origin pull/179/head:pr179
git checkout pr179
```

**Comment by adietish** [comment]
weird, now git knows about your branch, earlier it didnt. I assume some prob in github?
Well, anyhow, merging, thanks again.

**Comment by adietish** [comment]
merged

**Pull request closed without merging**
