### PR TITLE
[OSJC-200] fixing a couple of null reference issues via coverity

### PR DESCRIPTION
**Pull request by corey112358**

### CODE REVIEW

**Comment by corey112358** [comment]
[test]

**Comment by corey112358** [comment]
[test]

**Comment by corey112358** [comment]
@adietish @jcantrill Could one of you take a look at this when you get a chance?

**Comment by jcantrill** [comment]
LGTM

**Comment by adietish** [comment]
@corey112358 thx!
[merge]

**Comment by adietish** [comment]
test failure looks like a platform problem, not client problem. re-merging.
[merge]

**Pull request merged**
