### PR TITLE
Route support

### PR DESCRIPTION
**Pull request by tomason**
Implementation of route creation/retrieval/deletion from OpenShift 3 (tested with v0.4).

### CODE REVIEW

**Comment by adietish** [comment]
Thanks!!
@jcantrill  can you please review and merge this?

**Comment by jcantrill** [comment]
@adietish  @tomason Looks good to me.  Can you please squash into a singular commit?

**Comment by jcantrill** [comment]
@tomason @adietish I just realized that we are missing the termination info and keys and certs info required for a valid route other than 'unsecured'.  Please also add the tls block https://github.com/openshift/origin/blob/master/pkg/route/api/types.go#L23

**Comment by tomason** [comment]
How about this? I squashed commits into one and added all available fields (path and tls).

**Comment by tomason** [comment]
I have deleted comments committed by mistake. Also I added licence header to new files.

**Comment by jcantrill** [comment]
@tomason @adietish merged

**Pull request merged**
