### PR TITLE
Replication controller properties for display

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by jcantrill** [comment]
@adietish updates to support resource controller properties

**Comment by adietish** [comment]
+1, dont see anything harmful/not ideal.

**Comment by adietish** [comment]
rebased, merged and pushed to upstream/v3

**Comment by adietish** [comment]
and deployed SNAPSHOT to repository.jboss.org (for our CI to pick up when building JBT/JBDS)

**Pull request closed without merging**
